id = "one-dark-pro-max"
name = "One Dark Pro Max"
version = "0.0.2"
schema_version = 1
authors = ["Kusuma", "BoyeDarat"]
description = "One Dark Pro Max/Glass theme for Zed :)"
repository = "https://github.com/kussumma/one-dark-pro-max"
